#!/bin/bash

set -e -u

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <version>" >&2
  exit 1
fi

cd $(dirname $0)/..

version="$1"
shift

go install github.com/vito/booklit/cmd/booklit

booklit -i docs/lit/index.lit \
  --plugin github.com/concourse/docs/go/docs \
  --plugin github.com/concourse/docs/go/resource-type-list \
  --text-file-extension md \
  --text-templates md/ \
  --section-path lit/$version.lit \
  "$@"
